/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '찬희' at '17. 1. 15 오후 8:10' with Gradle 2.14.1
 *
 * @author 찬희, @date 17. 1. 15 오후 8:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
